server:
  port: 8675
#default port is 8765
spring:  application:    name: gateway-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
    
zuul:
  routes:    users:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    pets:
      path: /pets/**
      service-id: pet-service
      strip-prefix: false