server:
  port: 8084
spring:
  application:
    name: pet-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
feign:
  hystrix:    enabled: true